### PR TITLE
Carousel improvements

### PR DESCRIPTION
**Pull request by avikalpg**
1. Changed the `relevanceComment` image to the one without the tags
2. Multiple fixes in the CarouselBase component based on recommendations of CodeRabbit
3. Added the option to customize the `className`s of the CarouselItems from outside (via Prop propagation)
4. Updated the version of the application in package

## Summary by CodeRabbit

- **New Features**
	- Introduced a carousel component with navigation and autoplay functionality for a dynamic display of items.
	- Enhanced button components with additional properties for advanced styling and functionality.

- **Enhancements**
	- Updated the features section to utilize the new carousel component, improving user interaction and visual appeal.

### CODE REVIEW

**Comment by MuskanPaliwal** [comment]
Relevant users for this PR:

| Contributor Name/Alias  | Relevance |
| -------------- | --------------- |
| ajay.yadav@vibinex.com | 40.91% |
| avikalpgupta@gmail.com | 36.36% |
| tapish303@gmail.com | 18.18% |
| muskan10112002@gmail.com | 4.55% |


Auto assigning to all relevant reviewers

If you are a relevant reviewer, you can use the [Vibinex browser extension](https://chromewebstore.google.com/detail/vibinex-code-review/jafgelpkkkopeaefadkdjcmnicgpcncc) to see parts of the PR relevant to you
Relevance of the reviewer is calculated based on the git blame information of the PR. To know more, hit us up at contact@vibinex.com.

To change comment and auto-assign settings, go to [your Vibinex settings page.](https://vibinex.com/u)

**Review by tapishr — APPROVED** [review]
Jhakaas!

**Comment by MuskanPaliwal** [comment]
Relevant users for this PR:

| Contributor Name/Alias  | Relevance |
| -------------- | --------------- |
| avikalpgupta@gmail.com | 100.00% |


Auto assigning to all relevant reviewers

If you are a relevant reviewer, you can use the [Vibinex browser extension](https://chromewebstore.google.com/detail/vibinex-code-review/jafgelpkkkopeaefadkdjcmnicgpcncc) to see parts of the PR relevant to you
Relevance of the reviewer is calculated based on the git blame information of the PR. To know more, hit us up at contact@vibinex.com.

To change comment and auto-assign settings, go to [your Vibinex settings page.](https://vibinex.com/u)

**Comment by MuskanPaliwal** [comment]
Relevant users for this PR:

| Contributor Name/Alias  | Relevance |
| -------------- | --------------- |
| tapish303@gmail.com | 27.27% |
| avikalpgupta@gmail.com | 72.73% |


Auto assigning to all relevant reviewers

If you are a relevant reviewer, you can use the [Vibinex browser extension](https://chromewebstore.google.com/detail/vibinex-code-review/jafgelpkkkopeaefadkdjcmnicgpcncc) to see parts of the PR relevant to you
Relevance of the reviewer is calculated based on the git blame information of the PR. To know more, hit us up at contact@vibinex.com.

To change comment and auto-assign settings, go to [your Vibinex settings page.](https://vibinex.com/u)

**Review by MuskanPaliwal — APPROVED** [review]

**Comment by MuskanPaliwal** [comment]
Relevant users for this PR:

| Contributor Name/Alias  | Relevance |
| -------------- | --------------- |
| tapish303@gmail.com | 27.27% |
| avikalpgupta@gmail.com | 72.73% |


Auto assigning to all relevant reviewers

If you are a relevant reviewer, you can use the [Vibinex browser extension](https://chromewebstore.google.com/detail/vibinex-code-review/jafgelpkkkopeaefadkdjcmnicgpcncc) to see parts of the PR relevant to you
Relevance of the reviewer is calculated based on the git blame information of the PR. To know more, hit us up at contact@vibinex.com.

To change comment and auto-assign settings, go to [your Vibinex settings page.](https://vibinex.com/u)

**Pull request merged**
