### PR TITLE
Carousel UI fixes

### PR DESCRIPTION
**Pull request by avikalpg**
1. Fixes in the Carousel implementation
2. Added autoplay for carousels
3. Changed the image for the relevant-reviewer comment feature 
4. Improvements in the UI of the features section (size of the text, margins and alignments)
5. Fixes in the Button component related to incorrect merging of previous pull requests.

### CODE REVIEW

**Comment by avikalpg** [comment]
@tapishr Why was vibi-dpu not able to automatically assign the relevant handles as reviewers in this pull request?
(Please check if failing to add iitkshriya led to the failure to add other relevant reviewers)

**Review by MuskanPaliwal — APPROVED** [review]
good to go from my end

**Comment by MuskanPaliwal** [comment]
Relevant users for this PR:

| Contributor Name/Alias  | Relevance |
| -------------- | --------------- |
| tapish303@gmail.com | 4.26% |
| avikalpg@users.noreply.github.com | 4.26% |
| ajay.yadav@vibinex.com | 2.13% |
| avikalpgupta@gmail.com | 38.30% |
| iitkshriya@gmail.com | 51.06% |


Auto assigning to all relevant reviewers

If you are a relevant reviewer, you can use the [Vibinex browser extension](https://chromewebstore.google.com/detail/vibinex-code-review/jafgelpkkkopeaefadkdjcmnicgpcncc) to see parts of the PR relevant to you
Relevance of the reviewer is calculated based on the git blame information of the PR. To know more, hit us up at contact@vibinex.com.

To change comment and auto-assign settings, go to [your Vibinex settings page.](https://vibinex.com/u)

**Review by tapishr — APPROVED** [review]
LGTM

**Comment by MuskanPaliwal** [comment]
Relevant users for this PR:

| Contributor Name/Alias  | Relevance |
| -------------- | --------------- |
| iitkshriya@gmail.com | 51.06% |
| ajay.yadav@vibinex.com | 2.13% |
| avikalpgupta@gmail.com | 38.30% |
| tapish303@gmail.com | 4.26% |
| avikalpg@users.noreply.github.com | 4.26% |


Auto assigning to all relevant reviewers

If you are a relevant reviewer, you can use the [Vibinex browser extension](https://chromewebstore.google.com/detail/vibinex-code-review/jafgelpkkkopeaefadkdjcmnicgpcncc) to see parts of the PR relevant to you
Relevance of the reviewer is calculated based on the git blame information of the PR. To know more, hit us up at contact@vibinex.com.

To change comment and auto-assign settings, go to [your Vibinex settings page.](https://vibinex.com/u)

**Comment by MuskanPaliwal** [comment]
I am restoring the branch to reproduce the same comment issue.

**Pull request merged**
